-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE * PRODUCT2.cnt AS SALES
FROM PRODUCT JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS cnt
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) AS PRODUCT2 USING(PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE ASC;