-- 코드를 입력하세요
SELECT ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS as a
JOIN ANIMAL_OUTS as b USING(ANIMAL_ID)
WHERE SUBSTR(SEX_UPON_INTAKE, 1, 6) = 'Intact' and (SUBSTR(SEX_UPON_OUTCOME, 1, 6) = 'Spayed' or SUBSTR(SEX_UPON_OUTCOME, 1, 8) = 'Neutered')
ORDER BY ANIMAL_ID;