-- 코드를 입력하세요
SELECT FLAVOR
FROM 
(SELECT FLAVOR, SUM(TOTAL_ORDER) as A_ORDER
 FROM FIRST_HALF 
 GROUP BY FLAVOR) as a
 JOIN 
 (SELECT FLAVOR, SUM(TOTAL_ORDER) as B_ORDER
 FROM JULY
  GROUP BY FLAVOR) as b USING(FLAVOR)
ORDER BY A_ORDER + B_ORDER DESC
LIMIT 3;