-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM (
    SELECT *
    FROM APPOINTMENT
    JOIN PATIENT USING(PT_NO)
) as a
JOIN DOCTOR ON a.MDDR_ID = DOCTOR.DR_ID
WHERE a.MCDP_CD = "CS" and DATE(APNT_YMD) = DATE("2022-04-13") and APNT_CNCL_YMD is null
ORDER BY APNT_YMD;


